/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AccessLog = IDL.Record({
  'id' : IDL.Nat,
  'personName' : IDL.Text,
  'personId' : IDL.Nat,
  'timestamp' : Time,
  'location' : IDL.Text,
  'cameraId' : IDL.Nat,
  'accessStatus' : IDL.Bool,
});
export const Camera = IDL.Record({
  'onlineStatus' : IDL.Bool,
  'location' : IDL.Text,
  'cameraId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const SystemStatus = IDL.Record({
  'storageUsedPercent' : IDL.Nat,
  'uptime' : IDL.Nat,
  'onlineCamerasCount' : IDL.Nat,
  'activeNodes' : IDL.Nat,
});
export const VerificationRecord = IDL.Record({
  'id' : IDL.Nat,
  'personName' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'personId' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccessLog' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'addVerificationRecord' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccessLog' : IDL.Func([IDL.Nat], [AccessLog], ['query']),
  'getAccessLogsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AccessLog)],
      ['query'],
    ),
  'getAllCameras' : IDL.Func([], [IDL.Vec(Camera)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCamera' : IDL.Func([IDL.Nat], [Camera], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(VerificationRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCamera' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCameraStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AccessLog = IDL.Record({
    'id' : IDL.Nat,
    'personName' : IDL.Text,
    'personId' : IDL.Nat,
    'timestamp' : Time,
    'location' : IDL.Text,
    'cameraId' : IDL.Nat,
    'accessStatus' : IDL.Bool,
  });
  const Camera = IDL.Record({
    'onlineStatus' : IDL.Bool,
    'location' : IDL.Text,
    'cameraId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const SystemStatus = IDL.Record({
    'storageUsedPercent' : IDL.Nat,
    'uptime' : IDL.Nat,
    'onlineCamerasCount' : IDL.Nat,
    'activeNodes' : IDL.Nat,
  });
  const VerificationRecord = IDL.Record({
    'id' : IDL.Nat,
    'personName' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'personId' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccessLog' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'addVerificationRecord' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccessLog' : IDL.Func([IDL.Nat], [AccessLog], ['query']),
    'getAccessLogsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AccessLog)],
        ['query'],
      ),
    'getAllCameras' : IDL.Func([], [IDL.Vec(Camera)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCamera' : IDL.Func([IDL.Nat], [Camera], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(VerificationRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCamera' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCameraStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };