/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessLog {
  'id' : bigint,
  'personName' : string,
  'personId' : bigint,
  'timestamp' : Time,
  'location' : string,
  'cameraId' : bigint,
  'accessStatus' : boolean,
}
export interface Camera {
  'onlineStatus' : boolean,
  'location' : string,
  'cameraId' : bigint,
}
export interface SystemStatus {
  'storageUsedPercent' : bigint,
  'uptime' : bigint,
  'onlineCamerasCount' : bigint,
  'activeNodes' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationRecord {
  'id' : bigint,
  'personName' : string,
  'confidenceScore' : bigint,
  'personId' : bigint,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccessLog' : ActorMethod<
    [string, bigint, string, boolean, bigint],
    undefined
  >,
  'addVerificationRecord' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccessLog' : ActorMethod<[bigint], AccessLog>,
  'getAccessLogsPaginated' : ActorMethod<[bigint, bigint], Array<AccessLog>>,
  'getAllCameras' : ActorMethod<[], Array<Camera>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCamera' : ActorMethod<[bigint], Camera>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerificationHistory' : ActorMethod<
    [bigint, bigint],
    Array<VerificationRecord>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCamera' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCameraStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];